import type { Challenge, Post } from "./types";

export const SEED_CHALLENGE: Challenge = {
  title: "Minimal — low sugar, 3 days",
  body:
    "Three days, no added sugar. Fruit's fine, anything with a label isn't. The point isn't the diet — it's noticing how often we reach for it on autopilot. Logging slip-ups here.",
  started: "2026-05-01",
  ends: "2026-05-04",
  setBy: "guy",
};

export const SEED_POSTS: Post[] = [
  {
    id: "p10",
    author: "dan",
    type: "text",
    time: "2026-05-03T09:14:00.000Z",
    body:
      "Day 3. The afternoon coffee was the test. Drank it black, hated the first sip, was fine by the third. Going to keep it past Monday.",
    tags: ["challenge", "habits"],
    comments: [
      { id: "c1", author: "guy", time: "2026-05-03T09:40:00.000Z", body: "Same. The first 48hrs were a fog and then it cleared." },
      { id: "c2", author: "dan", time: "2026-05-03T10:02:00.000Z", body: "Fog is the right word for it." },
    ],
  },
  {
    id: "p9",
    author: "guy",
    type: "quote",
    time: "2026-05-02T20:11:00.000Z",
    body: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    attribution: "Will Durant (paraphrasing Aristotle)",
    tags: ["habits"],
    comments: [
      { id: "c3", author: "dan", time: "2026-05-02T21:00:00.000Z", body: "Convenient timing for our challenge." },
    ],
  },
  {
    id: "p8",
    author: "dan",
    type: "link",
    time: "2026-05-02T14:30:00.000Z",
    title: "The Pleasure of Doing Things Badly",
    source: "The Marginalian",
    url: "https://www.themarginalian.org/",
    excerpt: "On giving yourself permission to be an amateur — making things for the joy of making them, not for an outcome.",
    tags: ["creativity"],
    comments: [],
  },
  {
    id: "p7",
    author: "guy",
    type: "text",
    time: "2026-05-02T08:02:00.000Z",
    body: "Walked the long way to the studio. Noticed I think more clearly when I'm slightly bored. Phone stays in the bag tomorrow too.",
    tags: ["walks", "attention"],
    comments: [],
  },
  {
    id: "p6",
    author: "guy",
    type: "link",
    time: "2026-05-01T19:45:00.000Z",
    title: "How Buildings Learn",
    source: "Stewart Brand",
    url: "https://en.wikipedia.org/wiki/How_Buildings_Learn",
    excerpt: "Buildings that adapt over time end up loved. The ones designed to be perfect on day one almost never are.",
    tags: ["design", "books"],
    comments: [
      { id: "c4", author: "guy", time: "2026-05-01T20:00:00.000Z", body: "Feels true of relationships and codebases too." },
    ],
  },
  {
    id: "p5",
    author: "dan",
    type: "quote",
    time: "2026-05-01T11:20:00.000Z",
    body: "The cure for boredom is curiosity. There is no cure for curiosity.",
    attribution: "Dorothy Parker",
    tags: [],
    comments: [],
  },
  {
    id: "p4",
    author: "guy",
    type: "text",
    time: "2026-04-30T22:08:00.000Z",
    body: "Sketch idea: a small device that does nothing but show the time, the temperature, and one sentence you wrote yourself in the morning. Anti-notification.",
    tags: ["ideas", "design"],
    comments: [
      { id: "c5", author: "dan", time: "2026-04-30T22:30:00.000Z", body: "I'd buy that. Wood case." },
      { id: "c6", author: "guy", time: "2026-04-30T22:35:00.000Z", body: "Walnut. With a single brass screw." },
    ],
  },
  {
    id: "p3",
    author: "dan",
    type: "link",
    time: "2026-04-30T16:00:00.000Z",
    title: "Slow productivity",
    source: "Cal Newport",
    url: "https://calnewport.com/",
    excerpt: "Doing fewer things, working at a natural pace, obsessing over quality. Sounds obvious; almost no one does it.",
    tags: ["work"],
    comments: [],
  },
  {
    id: "p2",
    author: "guy",
    type: "text",
    time: "2026-04-29T07:45:00.000Z",
    body: "Trying to keep mornings as the place where the best work happens. Email after lunch, not before. Two days in.",
    tags: ["work", "habits"],
    comments: [],
  },
  {
    id: "p1",
    author: "dan",
    type: "quote",
    time: "2026-04-28T18:00:00.000Z",
    body: "If you can't explain it simply, you don't understand it well enough.",
    attribution: "Often attributed to Einstein",
    tags: [],
    comments: [],
  },
];
